### ISSUE TITLE
Go senior here, may I improve your server structure ?

### ISSUE THREAD

**Issue by notpersico** [cetorres/ai-buddy#3]

**Comment by cetorres** [comment]
Go ahead! 👍🏻 
I think now it's solving the problem, because it doesn't need too much.
Take a look at the code now, just updated the web UI.
But if you think you can improve it, great!

Just have in mind some requirements:
- Keep it simple. No separate files, one `server.go` file is enough.
- No external modules.
- The `static` folder needs to continue to be embed.
- The server needs to continue to stream the data to the JS side, I'm using `server sent events`.

If you can help in other fronts as well, like:
- On the web UI, right now the save settings is saving the API keys as environment variables, but not persisting. After the server restarts it gets the original ones set in the ~/.zshrc file (or other, according to the system).
- We could add support to Claude as well.

Thanks.

**Comment by cetorres** [comment]
I released v.1.1.5. Take a look. Thanks.
